backend: tensorflow
class_name: Sequential
config:
  build_input_shape: !!python/tuple [null, 32, 32, 1]
  layers:
  - class_name: Conv2D
    config:
      activation: relu
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      data_format: channels_last
      dilation_rate: &id001 !!python/tuple [1, 1]
      filters: 10
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config: {distribution: uniform, mode: fan_avg, scale: 1.0, seed: null}
      kernel_regularizer: null
      kernel_size: !!python/tuple [5, 5]
      name: conv2d_1
      padding: valid
      strides: &id002 !!python/tuple [1, 1]
      trainable: true
      use_bias: true
  - class_name: BatchNormalization
    config:
      axis: -1
      beta_constraint: null
      beta_initializer:
        class_name: Zeros
        config: {}
      beta_regularizer: null
      center: true
      epsilon: 0.001
      gamma_constraint: null
      gamma_initializer:
        class_name: Ones
        config: {}
      gamma_regularizer: null
      momentum: 0.99
      moving_mean_initializer:
        class_name: Zeros
        config: {}
      moving_variance_initializer:
        class_name: Ones
        config: {}
      name: batch_normalization_1
      scale: true
      trainable: true
  - class_name: Conv2D
    config:
      activation: relu
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      data_format: channels_last
      dilation_rate: *id001
      filters: 10
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config: {distribution: uniform, mode: fan_avg, scale: 1.0, seed: null}
      kernel_regularizer: null
      kernel_size: !!python/tuple [5, 5]
      name: conv2d_2
      padding: valid
      strides: *id002
      trainable: true
      use_bias: true
  - class_name: BatchNormalization
    config:
      axis: -1
      beta_constraint: null
      beta_initializer:
        class_name: Zeros
        config: {}
      beta_regularizer: null
      center: true
      epsilon: 0.001
      gamma_constraint: null
      gamma_initializer:
        class_name: Ones
        config: {}
      gamma_regularizer: null
      momentum: 0.99
      moving_mean_initializer:
        class_name: Zeros
        config: {}
      moving_variance_initializer:
        class_name: Ones
        config: {}
      name: batch_normalization_2
      scale: true
      trainable: true
  - class_name: MaxPooling2D
    config:
      data_format: channels_last
      name: max_pooling2d_1
      padding: valid
      pool_size: !!python/tuple [2, 2]
      strides: !!python/tuple [2, 2]
      trainable: true
  - class_name: Flatten
    config: {data_format: channels_last, name: flatten_1, trainable: true}
  - class_name: Dense
    config:
      activation: relu
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config: {distribution: normal, mode: fan_in, scale: 2.0, seed: null}
      kernel_regularizer: null
      name: dense_1
      trainable: true
      units: 2560
      use_bias: true
  - class_name: BatchNormalization
    config:
      axis: -1
      beta_constraint: null
      beta_initializer:
        class_name: Zeros
        config: {}
      beta_regularizer: null
      center: true
      epsilon: 0.001
      gamma_constraint: null
      gamma_initializer:
        class_name: Ones
        config: {}
      gamma_regularizer: null
      momentum: 0.99
      moving_mean_initializer:
        class_name: Zeros
        config: {}
      moving_variance_initializer:
        class_name: Ones
        config: {}
      name: batch_normalization_3
      scale: true
      trainable: true
  - class_name: Dense
    config:
      activation: relu
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config: {distribution: normal, mode: fan_in, scale: 2.0, seed: null}
      kernel_regularizer: null
      name: dense_2
      trainable: true
      units: 2560
      use_bias: true
  - class_name: BatchNormalization
    config:
      axis: -1
      beta_constraint: null
      beta_initializer:
        class_name: Zeros
        config: {}
      beta_regularizer: null
      center: true
      epsilon: 0.001
      gamma_constraint: null
      gamma_initializer:
        class_name: Ones
        config: {}
      gamma_regularizer: null
      momentum: 0.99
      moving_mean_initializer:
        class_name: Zeros
        config: {}
      moving_variance_initializer:
        class_name: Ones
        config: {}
      name: batch_normalization_4
      scale: true
      trainable: true
  - class_name: Dense
    config:
      activation: softmax
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      kernel_constraint: null
      kernel_initializer:
        class_name: VarianceScaling
        config: {distribution: uniform, mode: fan_avg, scale: 1.0, seed: null}
      kernel_regularizer: null
      name: dense_3
      trainable: true
      units: 46
      use_bias: true
  name: sequential_1
keras_version: 2.2.4
